[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "fix-byte-order-marker"

[[repos.hooks]]
id = "mixed-line-ending"
args = ["--fix=no"]

[[repos.hooks]]
id = "check-yaml"
args = ["--allow-multiple-documents"]
exclude = "^charts/.*/templates/"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-json"

[[repos.hooks]]
id = "check-added-large-files"

[[repos.hooks]]
id = "check-merge-conflict"

[[repos.hooks]]
id = "check-case-conflict"

[[repos.hooks]]
id = "check-illegal-windows-names"

[[repos.hooks]]
id = "check-symlinks"

[[repos.hooks]]
id = "destroyed-symlinks"

[[repos.hooks]]
id = "detect-private-key"
exclude = "^docs/plans/credentials\\.md$"

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "v0.48.0"

[[repos.hooks]]
id = "markdownlint-fix"
args = ["-p", ".markdownlintignore"]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.7"

[[repos.hooks]]
id = "ruff"
args = ["--fix"]

[[repos.hooks]]
id = "ruff-format"
