"use client";

import cronstrue from "cronstrue";
import "cronstrue/locales/de";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bot, Loader2, Pause, Play, Plus, RefreshCw, Save, Trash2, X } from "lucide-react";
import { useTranslations } from "next-intl";
import { EmojiText } from "@/components/emoji-text";
import {
  type AvailableModelInfo,
  createJob,
  deleteJob,
  fetchModels,
  listJobs,
  runJob,
  updateJob,
} from "@/lib/api";
import { useAppLocale } from "@/components/locale-provider";
import { ModelPicker, withSelectedModelOption } from "@/components/model-picker";
import { SESSION_OPTION_ORDER, SessionOptionTiles, type SessionOptionKey } from "@/components/session-option-tiles";
import { SwitchRow } from "@/components/switch-row";
import type { JobCronTrigger, JobDefinition, SessionInfo, SessionLatestJobRun } from "@/lib/types";
import { cn } from "@/lib/utils";

interface JobsViewProps {
  server: string;
  token: string;
  sessions: SessionInfo[];
  onSessionActivated: (session: SessionInfo) => void;
  requestedJobId?: string | null;
}

const CRON_EXAMPLE_EXPRESSIONS = [
  "*/15 * * * *",
  "0 * * * *",
  "0 7 * * *",
  "0 9 * * 1-5",
  "30 18 * * 1-5",
  "0 9 1 * *",
  "0 0 * * 0",
];

function browserTimeZone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
  } catch {
    return "UTC";
  }
}

function availableTimeZones(extraTimeZones: Array<string | null | undefined> = []): string[] {
  const values = new Set<string>(["UTC"]);
  for (const timeZone of extraTimeZones) {
    if (typeof timeZone === "string" && timeZone.trim()) {
      values.add(timeZone.trim());
    }
  }

  if (typeof Intl.supportedValuesOf === "function") {
    for (const timeZone of Intl.supportedValuesOf("timeZone")) {
      values.add(timeZone);
    }
  }

  return Array.from(values).sort((left, right) => left.localeCompare(right));
}

function createEmptyTrigger(timeZone: string): JobCronTrigger {
  return {
    type: "cron",
    expression: "",
    timezone: timeZone,
  };
}

function createEmptyJob(): JobDefinition {
  return {
    id: "",
    name: "",
    enabled: true,
    triggers: [],
    prompt: "",
    private: false,
    unattended: true,
    ask_mode: false,
    yolo_mode: false,
    archive_previous_sessions: false,
    persistent_session_id: null,
    agent_model_name: null,
    sentinel_model_name: null,
    title_model_name: null,
    memory_enabled: false,
  };
}

function normalizeJobDraft(draft: JobDefinition): JobDefinition {
  return {
    ...draft,
    id: draft.id.trim(),
    name: draft.name.trim(),
    prompt: draft.prompt.trim(),
    persistent_session_id: draft.persistent_session_id?.trim() || null,
    agent_model_name: draft.agent_model_name?.trim() || null,
    sentinel_model_name: draft.sentinel_model_name?.trim() || null,
    title_model_name: draft.title_model_name?.trim() || null,
    triggers: draft.triggers.map((trigger) => ({
      type: "cron" as const,
      expression: trigger.expression.trim(),
      timezone: trigger.timezone?.trim() || null,
    })),
  };
}

function formatSessionOption(session: SessionInfo): string {
  const label = session.title?.trim();
  if (!label) return session.session_id;
  return `${label} (${session.session_id})`;
}

function toKebabCaseId(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function JobsView({
  server,
  token,
  sessions,
  onSessionActivated,
  requestedJobId,
}: JobsViewProps) {
  const t = useTranslations("jobs");
  const tRoot = useTranslations();
  const { locale } = useAppLocale();
  const [detectedTimeZone] = useState(() => browserTimeZone());
  const [jobs, setJobs] = useState<JobDefinition[]>([]);
  const [selectedJobId, setSelectedJobId] = useState<string | "new">("new");
  const [draft, setDraft] = useState<JobDefinition>(createEmptyJob);
  const [availableModels, setAvailableModels] = useState<AvailableModelInfo[]>([]);
  const [isIdAutogenerated, setIsIdAutogenerated] = useState(true);
  const [openTriggerExamples, setOpenTriggerExamples] = useState<number | null>(null);
  const [runData, setRunData] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const selectedJobIdRef = useRef<string | "new">("new");
  const appliedRequestedJobIdRef = useRef<string | null>(null);
  const openTriggerExamplesRef = useRef<HTMLDivElement | null>(null);

  const formatCronText = useCallback((expression: string): string => {
    try {
      return cronstrue.toString(expression, {
        throwExceptionOnParseError: true,
        use24HourTimeFormat: true,
        locale,
      });
    } catch {
      try {
        return cronstrue.toString(expression, {
          throwExceptionOnParseError: true,
          use24HourTimeFormat: true,
        });
      } catch {
        return expression;
      }
    }
  }, [locale]);

  const describeCronExpression = useCallback((expression: string): { text: string; invalid: boolean } | null => {
    const trimmed = expression.trim();
    if (trimmed.length === 0) {
      return null;
    }

    try {
      return {
        text: formatCronText(trimmed),
        invalid: false,
      };
    } catch {
      return {
        text: t("cron.invalidExpression"),
        invalid: true,
      };
    }
  }, [formatCronText, t]);

  const summarizeJob = useCallback((job: JobDefinition): string => {
    if (job.triggers.length === 0) {
      return t("summary.onDemandOnly");
    }

    if (job.triggers.length === 1) {
      const [trigger] = job.triggers;
      const expression = trigger.expression.trim();
      if (!expression) {
        return t("summary.cronTriggerCount", { count: 1 });
      }

      try {
        return formatCronText(expression);
      } catch {
        return t("summary.cronTriggerCount", { count: 1 });
      }
    }

    return t("summary.cronTriggerCount", { count: job.triggers.length });
  }, [formatCronText, t]);

  const validateJobDraft = useCallback((nextDraft: JobDefinition): string | null => {
    if (!nextDraft.id.trim()) return t("validation.idRequired");
    if (!nextDraft.name.trim()) return t("validation.nameRequired");
    if (!nextDraft.prompt.trim()) return t("validation.promptRequired");

    if (
      nextDraft.persistent_session_id !== null
      && nextDraft.persistent_session_id !== undefined
      && !nextDraft.persistent_session_id.trim()
    ) {
      return t("validation.persistentSessionIdRequired");
    }

    if (nextDraft.ask_mode && nextDraft.yolo_mode) {
      return t("validation.askAndYoloMutuallyExclusive");
    }

    const persistentSessionId = nextDraft.persistent_session_id?.trim();
    if (persistentSessionId && nextDraft.unattended) {
      return t("validation.persistentSessionMustBeAttended");
    }
    if (persistentSessionId && (nextDraft.private || nextDraft.ask_mode || nextDraft.yolo_mode)) {
      return t("validation.sessionModesRequireFreshSession");
    }
    if (
      persistentSessionId
      && [
        nextDraft.agent_model_name,
        nextDraft.sentinel_model_name,
        nextDraft.title_model_name,
      ].some((value) => Boolean(value?.trim()))
    ) {
      return t("validation.modelOverridesRequireFreshSession");
    }

    const emptyTrigger = nextDraft.triggers.find((trigger) => !trigger.expression.trim());
    if (emptyTrigger) return t("validation.cronEmpty");

    const invalidTrigger = nextDraft.triggers.find(
      (trigger) => describeCronExpression(trigger.expression)?.invalid,
    );
    if (invalidTrigger) {
      return t("validation.cronInvalid", { expression: invalidTrigger.expression });
    }

    return null;
  }, [describeCronExpression, t]);

  function toggleJobSessionOption(key: SessionOptionKey): void {
    const nextValue = !draft[key];
    if (key === "unattended") {
      updateDraft({
        unattended: nextValue,
        persistent_session_id: nextValue ? null : draft.persistent_session_id,
      });
      return;
    }

    if (key === "ask_mode") {
      updateDraft({ ask_mode: nextValue, yolo_mode: nextValue ? false : draft.yolo_mode });
      return;
    }

    if (key === "yolo_mode") {
      updateDraft({ yolo_mode: nextValue, ask_mode: nextValue ? false : draft.ask_mode });
      return;
    }

    updateDraft({ private: nextValue });
  }

  const formatTriggerKindLabel = useCallback((triggerKind: SessionLatestJobRun["trigger_kind"]): string => {
    switch (triggerKind) {
      case "cron":
        return t("triggerKind.scheduled");
      case "api":
      case "manual":
        return t("triggerKind.manual");
      default:
        return triggerKind;
    }
  }, [t]);

  const formatLocalizedInvocationTimestamp = useCallback((value: string): string => {
    const parsed = Date.parse(value);
    if (Number.isNaN(parsed)) {
      return value;
    }

    return new Intl.DateTimeFormat(locale, {
      dateStyle: "medium",
      timeStyle: "short",
    }).format(parsed);
  }, [locale]);

  const selectableSessions = useMemo(
    () => sessions.filter((session) => !session.attributes.unattended && !session.attributes.archived),
    [sessions],
  );
  const timeZoneOptions = useMemo(
    () => availableTimeZones([detectedTimeZone, ...draft.triggers.map((trigger) => trigger.timezone)]),
    [detectedTimeZone, draft.triggers],
  );
  const agentModelOptions = useMemo(
    () => withSelectedModelOption(availableModels, draft.agent_model_name),
    [availableModels, draft.agent_model_name],
  );
  const sentinelModelOptions = useMemo(
    () => withSelectedModelOption(availableModels, draft.sentinel_model_name),
    [availableModels, draft.sentinel_model_name],
  );
  const selectedJob = useMemo(
    () => (selectedJobId === "new" ? null : jobs.find((job) => job.id === selectedJobId) ?? null),
    [jobs, selectedJobId],
  );

  const selectedJobInvocations = useMemo(
    () => {
      if (!selectedJob) {
        return [];
      }

      return sessions
        .filter((session) => session.latest_job_run?.job_id === selectedJob.id)
        .sort((left, right) => {
          const leftTime = Date.parse(left.latest_job_run?.triggered_at ?? left.last_active);
          const rightTime = Date.parse(right.latest_job_run?.triggered_at ?? right.last_active);
          const normalizedLeft = Number.isNaN(leftTime) ? 0 : leftTime;
          const normalizedRight = Number.isNaN(rightTime) ? 0 : rightTime;
          return normalizedRight - normalizedLeft;
        });
    },
    [selectedJob, sessions],
  );
  const cronExamples = useMemo(
    () => CRON_EXAMPLE_EXPRESSIONS.map((expression) => ({
      expression,
      description: formatCronText(expression),
    })),
    [formatCronText],
  );
  const normalizedDraft = useMemo(() => normalizeJobDraft(draft), [draft]);
  const draftValidationError = useMemo(() => validateJobDraft(normalizedDraft), [normalizedDraft, validateJobDraft]);
  const isDraftDirty = useMemo(() => {
    const baseline = selectedJob ? normalizeJobDraft(selectedJob) : createEmptyJob();
    return JSON.stringify(normalizedDraft) !== JSON.stringify(baseline);
  }, [normalizedDraft, selectedJob]);
  const visibleError = error ?? (isDraftDirty ? draftValidationError : null);

  function selectJob(nextJobs: JobDefinition[], nextSelectedJobId: string | "new"): void {
    if (nextSelectedJobId === "new") {
      selectedJobIdRef.current = "new";
      setSelectedJobId("new");
      setDraft(createEmptyJob());
      setIsIdAutogenerated(true);
      setOpenTriggerExamples(null);
      setRunData("");
      return;
    }

    const selectedJob = nextJobs.find((job) => job.id === nextSelectedJobId) ?? nextJobs[0];
    if (!selectedJob) {
      selectedJobIdRef.current = "new";
      setSelectedJobId("new");
      setDraft(createEmptyJob());
      setIsIdAutogenerated(true);
      setOpenTriggerExamples(null);
      setRunData("");
      return;
    }

    selectedJobIdRef.current = selectedJob.id;
    setSelectedJobId(selectedJob.id);
    setDraft(structuredClone(selectedJob));
    setIsIdAutogenerated(false);
    setOpenTriggerExamples(null);
    setRunData("");
  }

  useEffect(() => {
    let cancelled = false;

    fetchModels(server, token)
      .then((entries) => {
        if (!cancelled) {
          setAvailableModels(entries);
        }
      })
      .catch(() => {
        if (!cancelled) {
          setAvailableModels([]);
        }
      });

    async function load(): Promise<void> {
      setLoading(true);
      setError(null);
      try {
        const response = await listJobs(server, token);
        if (cancelled) return;

        setJobs(response.jobs);
        if (response.jobs.length === 0) {
          selectJob(response.jobs, "new");
          return;
        }

        const currentSelectedJobId = selectedJobIdRef.current;
        const nextSelectedJobId = currentSelectedJobId !== "new" && response.jobs.some((job) => job.id === currentSelectedJobId)
          ? currentSelectedJobId
          : response.jobs[0].id;
        selectJob(response.jobs, nextSelectedJobId);
      } catch (loadError) {
        if (cancelled) return;
        setError(loadError instanceof Error ? loadError.message : t("errors.load"));
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    void load();
    return () => {
      cancelled = true;
    };
  }, [server, t, token]);

  useEffect(() => {
    if (openTriggerExamples === null) {
      return;
    }

    function handlePointerDown(event: MouseEvent): void {
      if (!openTriggerExamplesRef.current?.contains(event.target as Node)) {
        setOpenTriggerExamples(null);
      }
    }

    document.addEventListener("mousedown", handlePointerDown);
    return () => {
      document.removeEventListener("mousedown", handlePointerDown);
    };
  }, [openTriggerExamples]);

  useEffect(() => {
    if (!notice) {
      return;
    }

    const timeout = window.setTimeout(() => {
      setNotice((current) => (current === notice ? null : current));
    }, 15_000);

    return () => {
      window.clearTimeout(timeout);
    };
  }, [notice]);

  useEffect(() => {
    if (!requestedJobId) {
      appliedRequestedJobIdRef.current = null;
      return;
    }

    if (appliedRequestedJobIdRef.current === requestedJobId || jobs.length === 0) {
      return;
    }

    if (!jobs.some((job) => job.id === requestedJobId)) {
      return;
    }

    const timer = window.setTimeout(() => {
      appliedRequestedJobIdRef.current = requestedJobId;
      selectedJobIdRef.current = requestedJobId;
      selectJob(jobs, requestedJobId);
      setError(null);
      setNotice(null);
    }, 0);

    return () => {
      window.clearTimeout(timer);
    };
  }, [jobs, requestedJobId]);

  function updateDraft(patch: Partial<JobDefinition>): void {
    setDraft((current) => ({ ...current, ...patch }));
  }

  function updateTrigger(index: number, patch: Partial<JobCronTrigger>): void {
    setDraft((current) => ({
      ...current,
      triggers: current.triggers.map((trigger, triggerIndex) =>
        triggerIndex === index ? { ...trigger, ...patch } : trigger,
      ),
    }));
  }

  async function refreshJobs(message?: string, preferredJobId: string | "new" = selectedJobId): Promise<void> {
    setLoading(true);
    setError(null);
    try {
      const response = await listJobs(server, token);
      setJobs(response.jobs);
      selectJob(response.jobs, preferredJobId);
      if (message) {
        setNotice(message);
      }
    } catch (refreshError) {
      setError(refreshError instanceof Error ? refreshError.message : t("errors.refresh"));
    } finally {
      setLoading(false);
    }
  }

  function handleCreateNew(): void {
    selectJob(jobs, "new");
    setError(null);
    setNotice(null);
  }

  async function handleSave(): Promise<void> {
    const normalizedDraft = normalizeJobDraft(draft);
    const validationError = validateJobDraft(normalizedDraft);
    if (validationError) {
      setError(validationError);
      setNotice(null);
      return;
    }

    setSaving(true);
    setError(null);
    setNotice(null);
    try {
      const saved = selectedJobId === "new"
        ? await createJob(server, token, normalizedDraft)
        : await updateJob(server, token, normalizedDraft.id, normalizedDraft);
      await refreshJobs(
        selectedJobId === "new" ? t("notices.created") : t("notices.saved"),
        saved.id,
      );
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : t("errors.save"));
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete(): Promise<void> {
    if (selectedJobId === "new") {
      handleCreateNew();
      return;
    }

    if (!window.confirm(t("confirmDelete", { name: draft.name || draft.id }))) {
      return;
    }

    setSaving(true);
    setError(null);
    setNotice(null);
    try {
      await deleteJob(server, token, draft.id);
      await refreshJobs(t("notices.deleted"), "new");
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : t("errors.delete"));
    } finally {
      setSaving(false);
    }
  }

  async function handleRun(): Promise<void> {
    if (selectedJobId === "new") {
      setError(t("errors.saveBeforeRun"));
      setNotice(null);
      return;
    }

    if (isDraftDirty) {
      setError(t("errors.saveChangesBeforeRun"));
      setNotice(null);
      return;
    }

    setRunning(true);
    setError(null);
    setNotice(null);
    try {
      const result = await runJob(server, token, draft.id, runData === "" ? undefined : runData);
      setNotice(result.created_new_session
        ? t("notices.runStartedNewSession", { sessionId: result.session_id })
        : t("notices.runStartedSession", { sessionId: result.session_id }));
    } catch (runError) {
      setError(runError instanceof Error ? runError.message : t("errors.run"));
    } finally {
      setRunning(false);
    }
  }

  const selectedSessionValue = draft.persistent_session_id ?? "";
  const usePersistentSession = draft.persistent_session_id !== null;
  const hasPersistentSessionId = Boolean(draft.persistent_session_id?.trim());
  const defaultModelLabel = tRoot("commandResult.models.default");

  return (
    <>
        <aside className="border-b border-border/80 bg-background/65 lg:border-r lg:border-b-0">
          <div className="flex h-full min-h-0 flex-col">
            <div className="flex items-center justify-between gap-3 border-b border-border/70 px-5 py-3">
              <div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">
                {t("savedJobs")}
              </div>
              <div className="flex items-center gap-1">
                <button
                  type="button"
                  onClick={() => void refreshJobs(t("notices.refreshed"))}
                  title={t("actions.refresh")}
                  aria-label={t("actions.refresh")}
                  className={cn(
                    "rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground disabled:opacity-60",
                    loading && "pointer-events-none",
                  )}
                  disabled={loading}
                >
                  <RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} />
                </button>
                <button
                  type="button"
                  onClick={handleCreateNew}
                  title={t("actions.new")}
                  aria-label={t("actions.new")}
                  className="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
                >
                  <Plus className="h-4 w-4" />
                </button>
              </div>
            </div>
            <div className="min-h-0 flex-1 overflow-y-auto p-3">
              {loading ? (
                <div className="flex items-center gap-2 rounded-xl border border-dashed border-border px-4 py-5 text-sm text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  {t("loading")}
                </div>
              ) : jobs.length === 0 ? (
                <div className="rounded-2xl border border-dashed border-border bg-background/80 px-4 py-6 text-sm text-muted-foreground">
                  {t("empty.noJobs")}
                </div>
              ) : (
                <div className="space-y-2">
                  {jobs.map((job) => {
                    const selected = selectedJobId === job.id;
                    return (
                      <button
                        key={job.id}
                        type="button"
                        onClick={() => {
                          selectJob(jobs, job.id);
                          setError(null);
                          setNotice(null);
                        }}
                        className={cn(
                          "w-full rounded-lg transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
                          selected
                            ? "bg-accent text-accent-foreground"
                            : "text-foreground/80 hover:bg-muted",
                        )}
                      >
                        <div className="flex items-start justify-between gap-3 px-3 pt-2 pb-1 text-left">
                          <div className="min-w-0">
                            <div className="truncate text-sm font-semibold">{job.name}</div>
                            <div className={cn(
                              "mt-0.5 truncate font-mono text-xs",
                              selected ? "text-accent-foreground/70" : "text-foreground/70",
                            )}>
                              {job.id}
                            </div>
                          </div>
                          {!job.enabled && (
                            <span className={cn(
                              "shrink-0 rounded-full px-2 py-0.5 text-[11px] font-medium flex items-center gap-1",
                              "bg-amber-100 text-amber-700",
                            )}>
                              <Pause className="h-3 w-3" />
                              {t("paused")}
                            </span>
                          )}
                        </div>
                        <div className={cn(
                          "px-3 pb-2 text-xs flex items-center justify-between gap-3",
                          selected ? "text-accent-foreground/70" : "text-foreground/70",
                        )}>
                          <span>{summarizeJob(job)}</span>
                          {job.unattended && (
                            <span
                              title={t("unattendedTooltip")}
                              className={cn(
                                "rounded-full p-1 inline-flex items-center",
                              )}
                            >
                              <Bot className={cn("h-4 w-4", selected ? "text-accent-foreground" : "text-emerald-700")} />
                            </span>
                          )}
                        </div>
                      </button>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </aside>

        <section className="min-h-0 overflow-y-auto px-5 py-5 sm:px-6">
          <div className="mx-auto flex max-w-4xl flex-col gap-4">
            <div className="flex flex-wrap items-center justify-between gap-3 rounded-3xl border border-border bg-background/88 px-5 py-4 shadow-sm">
              <p className="text-sm text-muted-foreground">
                {selectedJobId === "new"
                  ? t("editor.newJob")
                  : t("editor.editing", { name: draft.id || draft.name || t("editor.jobFallback") })}
              </p>
              <div className="flex flex-wrap items-center gap-2">
                {notice && !isDraftDirty ? <p className="text-sm text-emerald-700">{notice}</p> : null}
                <button
                  type="button"
                  onClick={() => void handleDelete()}
                  className="inline-flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2 text-sm font-medium text-destructive hover:bg-destructive/8 disabled:opacity-60"
                  disabled={saving || running}
                >
                  <Trash2 className="h-4 w-4" />
                  {selectedJobId === "new" ? t("actions.clear") : t("actions.delete")}
                </button>
                <button
                  type="button"
                  onClick={() => void handleSave()}
                  className="inline-flex items-center gap-2 rounded-lg bg-foreground px-3 py-2 text-sm font-medium text-background hover:bg-foreground/90 disabled:opacity-60 disabled:hover:bg-foreground"
                  disabled={saving || running || loading || draftValidationError !== null || !isDraftDirty}
                >
                  {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  {t("actions.save")}
                </button>
              </div>
            </div>

            <div className="rounded-3xl border border-border bg-background/88 p-5 shadow-sm">
              <div className="grid gap-4 md:grid-cols-2">
                <label className="space-y-1.5">
                  <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.name")}</span>
                  <input
                    value={draft.name}
                    onChange={(event) => {
                      const name = event.target.value;
                      const nextPatch: Partial<JobDefinition> = { name };

                      if (selectedJobId === "new" && isIdAutogenerated) {
                        nextPatch.id = toKebabCaseId(name);
                      }

                      updateDraft(nextPatch);
                    }}
                    placeholder={t("placeholders.name")}
                    disabled={saving || running}
                    className="w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-60"
                  />
                </label>
                <label className="space-y-1.5">
                  <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.jobId")}</span>
                  <input
                    value={draft.id}
                    onChange={(event) => {
                      const id = event.target.value;
                      setIsIdAutogenerated(selectedJobId === "new" && !id.trim());
                      updateDraft({ id });
                    }}
                    placeholder={t("placeholders.jobId")}
                    disabled={saving || running || selectedJobId !== "new"}
                    className="w-full rounded-xl border border-border bg-background px-3 py-2.5 font-mono text-sm outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-60"
                  />
                </label>
              </div>

              <div className="mt-4 space-y-3">
                <div className="space-y-3 rounded-2xl border border-border/70 bg-muted/35 px-4 py-3">
                  <SwitchRow
                    checked={draft.enabled}
                    label={t("fields.enabled")}
                    description={t("fields.enabledHelp")}
                    disabled={saving || running}
                    onCheckedChange={(enabled) => updateDraft({ enabled })}
                    className="rounded-xl border border-border/70 bg-background px-3 py-3"
                  />

                  <SwitchRow
                    checked={usePersistentSession}
                    label={t("fields.persistentSession")}
                    description={draft.unattended ? t("fields.persistentSessionDisabled") : t("fields.persistentSessionToggleHelp")}
                    disabled={saving || running || draft.unattended}
                    onCheckedChange={(enabled) =>
                      updateDraft({
                        persistent_session_id: enabled ? "" : null,
                        archive_previous_sessions: enabled ? false : draft.archive_previous_sessions,
                      })}
                    className="rounded-xl border border-border/70 bg-background px-3 py-3"
                  />
                </div>

                {!usePersistentSession ? (
                  <div className="space-y-3 rounded-2xl border border-border bg-muted/35 p-4">
                    <div className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.newSession")}</div>

                    <SessionOptionTiles
                      items={SESSION_OPTION_ORDER.map((key) => ({
                        key,
                        active: Boolean(draft[key]),
                        disabled: saving || running,
                        onClick: () => toggleJobSessionOption(key),
                      }))}
                    />

                    <SwitchRow
                      checked={draft.archive_previous_sessions}
                      label={t("fields.archivePreviousSessions")}
                      description={t("fields.archivePreviousSessionsHelp")}
                      disabled={saving || running}
                      onCheckedChange={(archive_previous_sessions) => updateDraft({ archive_previous_sessions })}
                      className="rounded-xl border border-border/70 bg-background px-3 py-3"
                    />
                  </div>
                ) : null}

                {usePersistentSession ? (
                  <div className="space-y-1.5 rounded-2xl border border-border bg-muted/35 p-4">
                    <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.persistentSession")}</span>
                    <div className="relative">
                      <input
                        list="jobs-session-options"
                        value={selectedSessionValue}
                        onChange={(event) => {
                          const persistentSessionId = event.target.value;
                          updateDraft({
                            persistent_session_id: persistentSessionId,
                            unattended: persistentSessionId.trim() ? false : draft.unattended,
                            archive_previous_sessions: persistentSessionId.trim() ? false : draft.archive_previous_sessions,
                            private: persistentSessionId.trim() ? false : draft.private,
                            ask_mode: persistentSessionId.trim() ? false : draft.ask_mode,
                            yolo_mode: persistentSessionId.trim() ? false : draft.yolo_mode,
                            agent_model_name: persistentSessionId.trim() ? null : draft.agent_model_name,
                            sentinel_model_name: persistentSessionId.trim() ? null : draft.sentinel_model_name,
                            title_model_name: persistentSessionId.trim() ? null : draft.title_model_name,
                          });
                        }}
                        placeholder={draft.unattended ? t("fields.persistentSessionDisabled") : t("placeholders.persistentSession")}
                        disabled={saving || running || draft.unattended}
                        className="w-full rounded-xl border border-border bg-background px-3 py-2.5 pr-10 font-mono text-sm outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-60"
                      />
                      {selectedSessionValue ? (
                        <button
                          type="button"
                          onClick={() => {
                            updateDraft({
                              persistent_session_id: "",
                            });
                          }}
                          aria-label={t("actions.clearPersistentSession")}
                          disabled={saving || running || draft.unattended}
                          className="absolute top-1/2 right-2 inline-flex h-7 w-7 -translate-y-1/2 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground disabled:cursor-not-allowed disabled:opacity-60"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      ) : null}
                    </div>
                    <datalist id="jobs-session-options">
                      {selectableSessions.map((session) => (
                        <option key={session.session_id} value={session.session_id} label={formatSessionOption(session)} />
                      ))}
                    </datalist>
                    <p className="text-xs text-muted-foreground">
                      {draft.unattended
                        ? t("fields.persistentSessionDisabled")
                        : hasPersistentSessionId
                          ? t("fields.persistentSessionActiveHelp")
                          : t("fields.persistentSessionMissingIdHelp")}
                    </p>
                  </div>
                ) : (
                  <div className="space-y-3 rounded-2xl border border-border bg-muted/35 p-4">
                    <div>
                      <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.models")}</span>
                      <p className="mt-1 text-xs text-muted-foreground">{t("fields.modelsHelp")}</p>
                    </div>
                    <div className="grid gap-3 xl:grid-cols-2">
                      <label className="space-y-1.5">
                        <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.agentModel")}</span>
                        <ModelPicker
                          value={draft.agent_model_name}
                          entries={agentModelOptions}
                          onChange={(value) => updateDraft({ agent_model_name: value })}
                          disabled={saving || running}
                          defaultLabel={defaultModelLabel}
                        />
                      </label>
                      <label className="space-y-1.5">
                        <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.sentinelModel")}</span>
                        <ModelPicker
                          value={draft.sentinel_model_name}
                          entries={sentinelModelOptions}
                          onChange={(value) => updateDraft({ sentinel_model_name: value })}
                          disabled={saving || running}
                          defaultLabel={defaultModelLabel}
                        />
                      </label>
                    </div>
                  </div>
                )}
              </div>

              <div className="mt-4">
                <label className="space-y-1.5">
                  <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.prompt")}</span>
                  <textarea
                    value={draft.prompt}
                    onChange={(event) => updateDraft({ prompt: event.target.value })}
                    placeholder={t("placeholders.prompt")}
                    disabled={saving || running}
                    rows={9}
                    className="w-full rounded-2xl border border-border bg-background px-3 py-3 text-sm outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-60"
                  />
                </label>
              </div>
            </div>

            <div className="rounded-3xl border border-border bg-background/88 p-5 shadow-sm">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <h2 className="text-lg font-semibold">{t("sections.cronTriggers")}</h2>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {t("sections.cronTriggersDescription")}
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => setDraft((current) => ({
                    ...current,
                    triggers: [...current.triggers, createEmptyTrigger(detectedTimeZone)],
                  }))}
                  className="inline-flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2 text-sm font-medium hover:bg-muted"
                  disabled={saving || running}
                >
                  <Plus className="h-4 w-4" />
                  {t("actions.addTrigger")}
                </button>
              </div>

              {draft.triggers.length === 0 ? (
                <div className="mt-4 rounded-2xl border border-dashed border-border px-4 py-5 text-sm text-muted-foreground">
                  {t("sections.noTriggers")}
                </div>
              ) : (
                <div className="mt-4 space-y-3">
                  {draft.triggers.map((trigger, index) => (
                    (() => {
                      const cronDescription = describeCronExpression(trigger.expression);
                      return (
                    <div
                      key={`${index}-${selectedJobId}`}
                      className="grid gap-3 rounded-2xl border border-border bg-muted/35 p-4 md:grid-cols-[minmax(0,1fr)_14rem_auto]"
                    >
                      <div className="space-y-1.5">
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.expression")}</span>
                        </div>
                        <div
                          ref={openTriggerExamples === index ? openTriggerExamplesRef : null}
                          className="relative"
                        >
                          <input
                            value={trigger.expression}
                            onChange={(event) => {
                              updateTrigger(index, { expression: event.target.value });
                              setOpenTriggerExamples(null);
                            }}
                            onFocus={() => setOpenTriggerExamples(index)}
                            onKeyDown={(event) => {
                              if (event.key === "Escape") {
                                setOpenTriggerExamples(null);
                              }
                            }}
                            role="combobox"
                            aria-expanded={openTriggerExamples === index}
                            aria-controls={`jobs-trigger-examples-${index}`}
                            disabled={saving || running}
                            className="w-full rounded-xl border border-border bg-background px-3 py-2.5 font-mono text-sm outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-60"
                          />
                          {openTriggerExamples === index ? (
                            <div
                              id={`jobs-trigger-examples-${index}`}
                              role="listbox"
                              className="absolute z-20 mt-2 max-h-72 w-full overflow-y-auto rounded-2xl border border-border bg-background p-2 shadow-xl"
                            >
                              <div className="space-y-1">
                                {cronExamples.map((example) => (
                                  <button
                                    key={example.expression}
                                    type="button"
                                    role="option"
                                    aria-selected={example.expression === trigger.expression.trim()}
                                    onClick={() => {
                                      updateTrigger(index, { expression: example.expression });
                                      setOpenTriggerExamples(null);
                                    }}
                                    className="w-full rounded-xl px-3 py-2 text-left transition-colors hover:bg-muted"
                                  >
                                    <div className="font-mono text-sm text-foreground">{example.expression}</div>
                                    <div className="mt-0.5 text-xs text-muted-foreground">{example.description}</div>
                                  </button>
                                ))}
                              </div>
                            </div>
                          ) : null}
                        </div>
                      </div>
                      <label className="space-y-1.5">
                        <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.timeZone")}</span>
                        <select
                          value={trigger.timezone ?? detectedTimeZone}
                          onChange={(event) => updateTrigger(index, { timezone: event.target.value || null })}
                          disabled={saving || running}
                          className="w-full rounded-xl border border-border bg-background px-3 py-2.5 font-mono text-sm outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-60"
                        >
                          {timeZoneOptions.map((timeZone) => (
                            <option key={timeZone} value={timeZone}>
                              {timeZone}
                            </option>
                          ))}
                        </select>
                      </label>
                      <div className="flex items-end md:self-end">
                        <button
                          type="button"
                          onClick={() => setDraft((current) => ({
                            ...current,
                            triggers: current.triggers.filter((_, triggerIndex) => triggerIndex !== index),
                          }))}
                          onMouseDown={() => setOpenTriggerExamples((current) => {
                            if (current === null) return null;
                            if (current === index) return null;
                            return current > index ? current - 1 : current;
                          })}
                          className="inline-flex h-[46px] items-center gap-2 rounded-lg border border-border bg-background px-3 py-2 text-sm font-medium text-destructive hover:bg-destructive/8"
                          disabled={saving || running}
                        >
                          <Trash2 className="h-4 w-4" />
                          {t("actions.remove")}
                        </button>
                      </div>
                      {cronDescription ? (
                        <p
                          className={cn(
                            "text-xs md:col-span-2",
                            cronDescription.invalid
                              ? "text-destructive"
                              : "text-muted-foreground",
                          )}
                        >
                          {cronDescription.text}
                        </p>
                      ) : null}
                    </div>
                      );
                    })()
                  ))}
                </div>
              )}
            </div>

            <div className="rounded-3xl border border-border bg-background/88 p-5 shadow-sm">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <h2 className="text-lg font-semibold">{t("sections.runJob")}</h2>
                </div>
                <button
                  type="button"
                  onClick={() => void handleRun()}
                  className="inline-flex items-center gap-2 rounded-lg border border-border bg-background px-3 py-2 text-sm font-medium hover:bg-muted disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:bg-background"
                  disabled={saving || running || selectedJobId === "new" || isDraftDirty}
                >
                  {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}
                  {t("actions.runNow")}
                </button>
              </div>
              <label className="mt-4 block space-y-1.5">
                <span className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{t("fields.inputOptional")}</span>
                <textarea
                  value={runData}
                  onChange={(event) => setRunData(event.target.value)}
                  disabled={saving || running}
                  rows={5}
                  className="w-full rounded-2xl border border-border bg-background px-3 py-3 font-mono text-sm outline-none transition-colors focus:border-ring focus:ring-2 focus:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-60"
                />
              </label>
            </div>

            <div className="rounded-3xl border border-border bg-background/88 p-5 shadow-sm">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <h2 className="text-lg font-semibold">{t("sections.previousInvocations")}</h2>
                  <p className="mt-1 text-sm text-muted-foreground">{t("sections.previousInvocationsDescription")}</p>
                </div>
              </div>

              {selectedJobId === "new" ? (
                <div className="mt-4 rounded-2xl border border-dashed border-border px-4 py-5 text-sm text-muted-foreground">
                  {t("sections.saveToViewHistory")}
                </div>
              ) : selectedJobInvocations.length === 0 ? (
                <div className="mt-4 rounded-2xl border border-dashed border-border px-4 py-5 text-sm text-muted-foreground">
                  {t("sections.noInvocations")}
                </div>
              ) : (
                <div className="mt-4 space-y-2">
                  {selectedJobInvocations.map((session) => {
                    const latestJobRun = session.latest_job_run;
                    if (!latestJobRun) {
                      return null;
                    }

                    return (
                      <button
                        key={session.session_id}
                        type="button"
                        onClick={() => onSessionActivated(session)}
                        className="w-full rounded-2xl border border-border bg-background/90 px-4 py-3 text-left transition-colors hover:bg-muted"
                        disabled={saving || running}
                      >
                        <div className="flex items-center justify-between gap-3">
                          <div className="min-w-0">
                            <div className="truncate text-sm font-medium text-foreground">
                              {session.title?.trim() ? <EmojiText text={session.title.trim()} /> : session.session_id}
                            </div>
                            <div className="mt-1 truncate font-mono text-xs text-muted-foreground">{session.session_id}</div>
                          </div>
                          <span className="shrink-0 rounded-full bg-muted px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                            {formatTriggerKindLabel(latestJobRun.trigger_kind)}
                          </span>
                        </div>
                        <div className="mt-2 text-xs text-muted-foreground">
                          {t("sections.ranAt", { timestamp: formatLocalizedInvocationTimestamp(latestJobRun.triggered_at) })}
                        </div>
                      </button>
                    );
                  })}
                </div>
              )}
            </div>

            {visibleError ? (
              <div className="rounded-2xl border border-border bg-background/88 px-4 py-3 text-sm shadow-sm">
                <p className="text-destructive">{visibleError}</p>
              </div>
            ) : null}

          </div>
        </section>
    </>
  );
}
