apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carapace

resources:
  - namespace.yaml
  - pvc.yaml
  - rbac.yaml
  - deployment-server.yaml
  - service-server.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - ingress.yaml
  - networkpolicy.yaml
