{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "carapace.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    app.kubernetes.io/name: carapace
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
{{- end }}
