apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "carapace.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: carapace
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
  ports:
    - name: api
      port: 8321
      targetPort: api
    - name: proxy
      port: 3128
      targetPort: proxy
