"""Render current memory records into the Markdown mirror in the user's knowledge repo.

Pure: records in, ``{repo-relative path: file content}`` out. The mirror handler writes exactly
these files under ``memory/`` and deletes everything else there, so a removed record removes its
file. Output is deterministic, so unchanged records produce no diff and no commit.
"""

from __future__ import annotations

import posixpath
from collections.abc import Iterable, Mapping, Sequence
from datetime import date
from typing import Any

import yaml

from .models import (
    DigestFact,
    DigestLevel,
    DigestRecord,
    DigestTheme,
    ExtractionRecord,
    Fact,
    FactCategory,
)

MIRROR_ROOT = "memory"

_CATEGORY_HEADINGS = {
    FactCategory.user: "You",
    FactCategory.social: "People",
    FactCategory.surroundings: "Surroundings",
}

README = """\
# Memory

Generated by carapace from your archived sessions. **Do not edit: every change here is
overwritten** on the next mirror run. The source of truth is carapace's database; manage memory
in the Memory area of the web UI.

- `sessions/YYYY/MM/<session id>.md`: what one session was about, its outcomes, open loops and
  the facts learned from it. `#42` refers to event 42 of the session.
- `weeks/YYYY-Www.md`: the digest of one ISO week, built from that week's sessions.
- `months/YYYY-MM.md`: the digest of one month, built from the weeks whose Thursday falls into it.

Every file starts with YAML front matter recording how it was produced: model, prompt version,
input hash, cost and, for digests, which sources it covers.
"""


def render_mirror(extractions: Sequence[ExtractionRecord], digests: Sequence[DigestRecord]) -> dict[str, str]:
    """Render the current *extractions* and *digests* of one user into mirror files."""
    stale = [f"extraction {r.id}" for r in extractions if not r.is_current]
    stale += [f"digest {r.id}" for r in digests if not r.is_current]
    if stale:
        raise ValueError(f"mirror renders current records only, got {', '.join(stale)}")

    ref_paths = {r.session_id: session_path(r) for r in extractions}
    ref_paths |= {r.period_key: digest_path(r) for r in digests if r.level is DigestLevel.week}
    files = {f"{MIRROR_ROOT}/README.md": README}
    files |= {session_path(r): render_session(r) for r in extractions}
    files |= {digest_path(r): render_digest(r, ref_paths) for r in digests}
    return files


def session_path(record: ExtractionRecord) -> str:
    year, month = record.month_key.split("-")
    return f"{MIRROR_ROOT}/sessions/{year}/{month}/{record.session_id}.md"


def digest_path(record: DigestRecord) -> str:
    folder = "weeks" if record.level is DigestLevel.week else "months"
    return f"{MIRROR_ROOT}/{folder}/{record.period_key}.md"


def render_session(record: ExtractionRecord) -> str:
    front_matter = {
        "kind": "session",
        **record.model_dump(mode="json", include={"session_id", "week_key", "month_key", "created_at", "provenance"}),
    }
    extraction = record.extraction
    facts = {
        category: [f"{_fact_line(f)}{_fact_meta(f, [f'#{seq}' for seq in f.source_seqs])}" for f in group]
        for category, group in _by_category(extraction.facts).items()
    }
    body = [
        f"# Session {record.session_id}",
        extraction.abstract,
        _section("Outcomes", extraction.outcomes),
        _section("Open loops", extraction.open_loops),
        _section("On my mind", extraction.on_my_mind),
        _fact_sections(facts),
        _section("Friction", extraction.friction),
        "## Tags\n\n" + " ".join(f"`{tag}`" for tag in extraction.tags) if extraction.tags else "",
    ]
    return _document(front_matter, body)


def render_digest(record: DigestRecord, ref_paths: Mapping[str, str]) -> str:
    """*ref_paths* maps refs (session ids, week keys) to mirror paths; known refs become links."""
    own_dir = posixpath.dirname(digest_path(record))

    def refs(values: Iterable[str]) -> str:
        return ", ".join(
            f"[{ref}]({posixpath.relpath(ref_paths[ref], own_dir)})" if ref in ref_paths else ref for ref in values
        )

    front_matter = {
        "kind": record.level.value,
        **record.model_dump(
            mode="json", include={"period_key", "created_at", "coverage", "coverage_hash", "provenance"}
        ),
    }
    digest = record.digest
    learned = {
        category: [f"{_fact_line(f)}{_fact_meta(f, [refs(f.refs)])}" for f in group]
        for category, group in _by_category(digest.learned).items()
    }
    body = [
        f"# {_period_title(record)}",
        digest.summary,
        _section("On my mind", [_theme_line(theme, refs(theme.refs)) for theme in digest.on_my_mind]),
        _section("Highlights", digest.highlights),
        _section("Open loops", digest.open_loops),
        _fact_sections(learned, heading="Learned"),
    ]
    return _document(front_matter, body)


def _period_title(record: DigestRecord) -> str:
    if record.level is DigestLevel.month:
        return f"Month {record.period_key}"
    year, week = record.period_key.split("-W")
    monday = date.fromisocalendar(int(year), int(week), 1)
    sunday = date.fromisocalendar(int(year), int(week), 7)
    return f"Week {record.period_key} ({monday.isoformat()} to {sunday.isoformat()})"


def _by_category[FactT: (Fact, DigestFact)](facts: Iterable[FactT]) -> dict[FactCategory, list[FactT]]:
    grouped: dict[FactCategory, list[FactT]] = {category: [] for category in FactCategory}
    for fact in facts:
        grouped[fact.category].append(fact)
    return grouped


def _fact_line(fact: Fact | DigestFact) -> str:
    return f"**{fact.subject}**: {fact.statement}" if fact.subject else fact.statement


def _fact_meta(fact: Fact | DigestFact, sources: list[str]) -> str:
    durability = f"dated until {fact.valid_until.isoformat()}" if fact.valid_until else fact.durability.value
    meta = [fact.source_kind.value, f"{fact.confidence.value} confidence", durability, *sources]
    return f" _({' · '.join(meta)})_"


def _theme_line(theme: DigestTheme, refs: str) -> str:
    return f"{theme.theme} ({refs})" if refs else theme.theme


def _fact_sections(facts: Mapping[FactCategory, list[str]], *, heading: str = "Facts") -> str:
    sub_sections = [_section(_CATEGORY_HEADINGS[c], lines, level=3) for c, lines in facts.items()]
    present = [s for s in sub_sections if s]
    return "\n\n".join([f"## {heading}", *present]) if present else ""


def _section(title: str, lines: Sequence[str], *, level: int = 2) -> str:
    if not lines:
        return ""
    return f"{'#' * level} {title}\n\n" + "\n".join(f"- {line}" for line in lines)


def _document(front_matter: dict[str, Any], body: list[str]) -> str:
    header = yaml.safe_dump(front_matter, sort_keys=False, allow_unicode=True, width=1000)
    return f"---\n{header}---\n\n" + "\n\n".join(part for part in body if part) + "\n"
